import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createEventBus} from '../bus/index.js';
import {validateEvent} from '../validation/index.js';
const base=JSON.parse(readFileSync(new URL('../fixtures/valid/activity.started.json',import.meta.url)));
const completion=JSON.parse(readFileSync(new URL('../fixtures/valid/activity.completed.json',import.meta.url)));
const event=(sequence,other={})=>({...base,id:'00000000-0000-4000-8000-'+String(1000+sequence).padStart(12,'0'),sequence,...other});
const options={activityId:base.activityId,sessionId:base.sessionId,sourceId:base.sourceId,validate:validateEvent};
const diagnostics=[],bus=createEventBus({...options,onDiagnostic:d=>diagnostics.push(d.code)}),trace=[];
const unsubscribe=bus.subscribe(e=>{trace.push('a'+e.sequence);assert(Object.isFrozen(e.payload));});
bus.subscribe(e=>trace.push('b'+e.sequence));
assert.deepEqual(bus.publish(event(0)),{accepted:true,delivery:'delivered'});unsubscribe();unsubscribe();bus.publish(event(1));assert.deepEqual(trace,['a0','b0','b1']);
assert.equal(bus.publish(event(1)).code,'bus.duplicate');
assert.equal(bus.publish(event(1,{timestamp:1})).code,'bus.conflict');
assert.equal(bus.publish(event(4)).code,'bus.sequence');assert.equal(bus.stats().nextSequence,2);
assert.equal(bus.publish(event(2,{sessionId:'00000000-0000-4000-8000-000000000099'})).code,'bus.identity');
assert.equal(bus.publish({...event(2),type:'bad'}).code,'bus.invalid');
const replay=[];const stop=bus.subscribe(e=>replay.push(e.sequence),{replay:true});assert.deepEqual(replay,[0,1]);bus.publish(event(2));assert.deepEqual(replay,[0,1,2]);stop();
const nested=createEventBus(options),ordered=[];let later;
nested.subscribe(e=>{ordered.push('a'+e.sequence);if(e.sequence===0){later=nested.publish(event(1));}});
nested.subscribe(e=>ordered.push('b'+e.sequence));nested.publish(event(0));assert.deepEqual(ordered,['a0','b0','a1','b1']);assert.equal(later.delivery,'queued');
const removing=createEventBus(options),seen=[];let removeB;
removing.subscribe(()=>removeB());removeB=removing.subscribe(()=>seen.push('removed'));removing.publish(event(0));assert.deepEqual(seen,[]);
const installing=createEventBus(options),installed=[];
installing.subscribe(e=>{if(e.sequence===0)installing.subscribe(v=>installed.push(v.sequence),{replay:true});});
installing.publish(event(0));installing.publish(event(1));assert.deepEqual(installed,[0,1]);
let committed=false;const isolated=createEventBus({...options,onDiagnostic:()=>{throw Error('Diagnostic observer');}});
isolated.subscribe(()=>{throw Error('Private subscriber error');});isolated.subscribe(()=>assert(committed));
committed=true;assert(isolated.publish(event(0,{...completion,id:event(0).id,sequence:0})).accepted);assert(committed);
const asyncErrors=[];const asyncBus=createEventBus({...options,onDiagnostic:d=>asyncErrors.push(d.code)});
asyncBus.subscribe(async()=>{throw Error('Async subscriber');});asyncBus.publish(event(0));await new Promise(resolve=>setImmediate(resolve));assert.deepEqual(asyncErrors,['bus.subscriber']);
const bounded=createEventBus({...options,maxPending:1,maxPerFlush:1,maxHistory:1}),receipts=[];
bounded.subscribe(e=>{if(e.sequence===0){receipts.push(bounded.publish(event(1)));receipts.push(bounded.publish(event(2)));}});
bounded.publish(event(0));assert.equal(receipts[0].accepted,true);assert.equal(receipts[1].code,'bus.backpressure');assert.equal(bounded.stats().pending,1);assert.equal(bounded.stats().nextSequence,2);bounded.flush();assert.equal(bounded.stats().pending,0);assert(bounded.publish(event(2)).accepted);
assert.equal(bounded.publish(event(0)).code,'bus.sequence','Evicted replay does not allow old source sequences');
const byteLimited=createEventBus({...options,maxPendingBytes:1});assert.equal(byteLimited.publish(event(0)).code,'bus.backpressure');assert.equal(byteLimited.stats().nextSequence,0);
const noHistory=createEventBus({...options,maxHistory:0});noHistory.publish(event(0));const noReplay=[];noHistory.subscribe(e=>noReplay.push(e),{replay:true});assert.deepEqual(noReplay,[]);
const cleanup=createEventBus(options);cleanup.subscribe(()=>cleanup.dispose());cleanup.subscribe(()=>assert.fail('Disposed observer ran'));cleanup.publish(event(0));assert.equal(cleanup.stats().disposed,true);assert.equal(cleanup.stats().subscribers,0);assert.equal(cleanup.stats().pendingBytes,0);assert.equal(cleanup.stats().historyBytes,0);cleanup.dispose();assert.equal(cleanup.publish(event(1)).code,'bus.disposed');assert.throws(()=>cleanup.subscribe(()=>{}),e=>e.code==='bus.disposed');
const limited=createEventBus({...options,maxSubscribers:1});limited.subscribe(()=>{});assert.throws(()=>limited.subscribe(()=>{}),e=>e.code==='bus.subscribers');
const rejected=createEventBus({...options,validate:async()=>{throw Error('Invalid async validator');}});assert.equal(rejected.publish(event(0)).code,'bus.invalid');await new Promise(resolve=>setImmediate(resolve));
const privacy=diagnostics.every(code=>typeof code==='string'&&code.startsWith('bus.'));assert(privacy);
console.log('Event bus: ordered/reentrant delivery, replay, duplicates, pressure, state/failure isolation, async rejection and disposal passed.');
